name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "vishali07" --password "${{ secrets.DOCKER_PASSWORD }}"
        docker image build -t python-flask-docker-githubactions:latest .
        docker push python-flask-docker-githubactions:latest
